server_version: 83
database:
    jdbc: jdbc:mysql://127.0.0.1/maplestory?autoReconnect=true&useSSL=false
    user: root
    pass: 1234
    verbose: false
server:
    login_port: 8484
    channel_ports: 8485
    channel_load: 50
    pic_enabled: true
    character_slots: 6
    channel_server_ip: 127.0.0.1
    kick_on_error: false
    cache_scripts: false
    auto_register: true
game:
    allow_beginner_parties: false
    map_unloading:
        enabled: false
        unload_time: 5000
        neighbor_threshold: 1
    default_cash_item_expire: 1296000000
    cache_wallets: true
    auto_save:
        enabled: true
        interval: 300000
    rates:
        exp: 50
        meso: 10
        quest: 10
        drop: 5
    